description: <p>An application profile based on the Dublin Core Metadata Initiative
  Abstract Model, used to describe multi-disciplinary data underlying peer-reviewed
  scientific and medical literature.</p>
identifiers:
- id: msc:m55
  scheme: RDA-MSCWG
keywords:
- Multidisciplinary
locations:
- type: website
  url: http://wiki.datadryad.org/Metadata_Profile
- type: namespace
  url: http://datadryad.org/metadata/
- type: XSD
  url: http://datadryad.org/profile/v3.1/dryad.xsd
- type: XSD
  url: http://datadryad.org/profile/v3/dryad.xsd
- type: XSD
  url: http://ils.unc.edu/mrc/dryad/version1_0/dryad_1_0.xsd
relatedEntities:
- id: msc:m15
  role: parent scheme
title: Dryad Metadata Application Profile
